import type sanitize from 'hast-util-sanitize';

export const MARKDOWN_HTML_SANITIZE_SCHEMA: sanitize.Schema = {
  ancestors: {
    tbody: ['table'],
    td: ['table'],
    tfoot: ['table'],
    th: ['table'],
    thead: ['table'],
    tr: ['table'],
  },
  attributes: {
    '*': [
      'abbr',
      'align',
      'alt',
      'ariaDescribedBy',
      'ariaHidden',
      'ariaLabel',
      'ariaLabelledBy',
      'checked',
      'className',
      'colSpan',
      'dateTime',
      'disabled',
      'height',
      'hrefLang',
      'id',
      'lang',
      'open',
      'rel',
      'rowSpan',
      'scope',
      'src',
      'style',
      'target',
      'title',
      'type',
      'width',
    ],
    a: ['href', 'name'],
    blockquote: ['cite'],
    del: ['cite'],
    img: ['alt', 'height', 'longDesc', 'src', 'title', 'width'],
    input: [['type', 'checkbox'], ['disabled', true], ['checked', true], 'className'],
    ins: ['cite'],
    q: ['cite'],
  },
  clobber: [],
  clobberPrefix: '',
  protocols: {
    cite: ['http', 'https'],
    href: ['http', 'https', 'mailto', 'xmpp', 'irc', 'ircs'],
    longDesc: ['http', 'https'],
    src: ['http', 'https', 'data'],
  },
  required: {
    input: {
      disabled: true,
      type: 'checkbox',
    },
  },
  strip: ['script', 'style'],
  tagNames: [
    'a',
    'abbr',
    'b',
    'blockquote',
    'br',
    'caption',
    'cite',
    'code',
    'dd',
    'del',
    'details',
    'dfn',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'input',
    'ins',
    'kbd',
    'li',
    'mark',
    'ol',
    'p',
    'pre',
    'q',
    's',
    'small',
    'span',
    'strike',
    'strong',
    'sub',
    'summary',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'tt',
    'ul',
    'var',
    'wbr',
  ],
};
